---
title: "quad_chart_2018_09_12"
author: "MTL Launch Workgroup"
date: "12 September 2018"
output: github_document = default
---
### R Markdown template for publishing workgroup quad_charts to GitHub. 

Enduring Issues (Parking Lot Issues)           |        Issues and Dependencies for Immediate Resolution
------------------------- | ----------------------------
Issue 1 LZ & TR - Workshop all "i" information in main tile to be clinician-friendly |Issue 1 
Issue 2                        |Issue 2 
Issue 3                        |Issue 3 
Issue 4                        |Issue 4
Issue 5                        |Issue 5   
Issue 6                        |Issue 6
Issue 7                        |Issue 7 
Issue 8                        |Issue 8

Actions Completed since Last Week    |      Workgroup Action Items to Complete This Week
------------------------- | ----------------------------
Action 1 Send source code in bug reports for rendering issues                       |Action 1 Sig figs: James will look into truncating model calculations with developers at output level prevent wildly oscilllating charts
Action 2 Appt supply = 75th percentil in PSY; median in AGG                       |Action 2 James - Add "i" info to MM in "Appointments for Existing Patients"
Action 3 Save & reset to access experiments in experiment tile/expanded ouputs                       |Action 3 James - Add "bc" button for all green experiment sliders like the one in Agg's "Appropriate Service Proportions from Supply"
Action 4 Updated "i" information for "Measured vs. Actual Time" in CC                       |Action 4 Tom - New name for "Appropriate Service Proportions from Supply" -> "Service proportions matched across model variables."
Action 5                        |Action 5 Bring the Q/H/F/D icons into the session guides (see and say)
Action 6                        |Action 6
Action 7                        |Action 7
Action 8                        |Action 8
