---
title: "Suicide Prevention Priority Questions"
author: "Team PSD"
date: "September 2018"
output: 
  github_document: default
  html_document: default
  pdf_document: default
  word_document: default
  ioslides_presentation: default
  slidy_presentation: default
  powerpoint_presentation: default
---

Rated on scale of: a lot / somewhat / very little
1. How  much do each of the following matter to getting and keeping patients in the right level of care?
- Start Rates to a team, comprising both new patients and concurrent transfer patients.
- Rate at which patients are assigned a high risk for suicide flag   while in treatment in a team
- Average time to remove a high risk flag from a patient in a team
- For patients with a high risk for suicide flag, the average time   before the patient is referred to another location.
- Average time in care before being stepped up or down to a different   setting
- Average time patients are engaged in care before they quit
- Average wait time for a transfer (i.e., the gap between a patient’s   last visit in the referring location and the first visit in the destination   location)
- The proportion of patients who have “high” symptoms in a team

2. How much do each of the following patient flow patterns matter to getting and keeping patients in the right level of care?
- PCMHI -> GMH
- PCMHI -> SMH
- PC -> Ending Treatment
- PCMHI -> InPt and Residential Tx
- HRFlag Pts in PCMHI -> GMH
- GMH -> PC
- GMH -> Ending Treatment
- GMH -> SMH
- GMH -> InPt and Residential Tx
- GMH -> Choice
- SMH -> PC
- SMH -> Ending Treatment
- SMH -> GMH
- SMH -> InPt and Residential Tx
- HRFlag Pts in SMH -> GMH
- SMH -> Choice

3. If a team is overburdened (i.e., has more patients in care than they have time to treat effectively), then how much do each of these consequences matter to getting and keeping patients in the right level of care?

- Team fatigue affects their care quality and patient compliance
- Team fatigue affects whether a patient receives a high risk for   suicide flag or has a flag removed
- Team fatigue affects how long it takes for the provides on the team   to recognize significant changes in patient symptoms
- Team fatigue affects how many new transfers the team accepts
- Team fatigue affects which patients the team refers out
- Team fatigue affects burnout and eventually increases the sick time   used and providers leaving the team
- Higher wait times to start care in the overburdened team affect other   teams’ referral rates to this team

4)	If a team is overburdened (i.e., has more patients in care than they have time to treat effectively), then how much do each of these consequences matter to getting and keeping patients in the right level of care?

- Team fatigue affects whether a patient receives a high risk for suicide flag or has a flag removed
- Team fatigue affects how long it takes for the provides on the team to recognize significant changes in patient symptoms
- Team fatigue affects how many new transfers the team accepts
- Team fatigue affects which patients the team refers out
- Team fatigue affects burnout and eventually increases the sick time used and providers leaving the team
- Higher wait times to start care in the overburdened team affect other teams’ referral rates to this team


