## Sticky
1. Going to be a very cool tool. Focus on what is actually affecting things in the system
2. We have dashboards that show data, but this is a tool that uses that data. 
3. Interactability
4. Can make specific decisions in a way that you have to extrapolate from other decisions. 
5. We can make hypotheses, but usually it takes 3-5 months to see effect. Shows decisions quickly.
6. Can see complexity of issue w/majority of pieces.
7. Dashboards in a thousand places. Lot of frontline staff tend to discount data. Makes data more approachable and less intimidating.  Still don't understand other dashboards/can't make it do what they want. Being able to customize data into exactly what you want and need without needing to know programming. Sim brings data to life in a visual way.
8. Data - I don't have to know what to click to get it. Doesn't seem like I can break it.
9. For seasoned staff, Excel spreadsheet is approachable and easy to use. By having it so specific to encounters, a clinician can look at that and look at the individual patients. They can filter and sort into something that makes sense for them.
10. Plus and minus: plus is additive or positive. negative is inverse effect. Feedback loops. Odd # of neg signs = balancing loop. Even # of neg signs = reinforcing loop. Virtuous or vicious.

## Session 7 Questions/Notes
- How do I get my data in?
- Is the Q/H/F/D dynamic per run or static over all runs?
- How do we save text put in Q/H/F/D
- What is basecase?
- I'd be interested in knowing current wait times and EBP delivery in services?
- Why would we hypothesize that things stay the same if our goal is to improve? Why don't we hypothesize to improve access with a certain change?
- I thought we were never supposed to hypothesize the null
- Why would we spend our time looking at the (basecase) hypothesis (where nothing is changing)
- What are we looking at from the starting point today?
- What are we doing and where are we going?
- We haven't talked about data showing up on our screens
- Running basecase and using it as comparison assumes that things happened before happened intentionally and aren't random
- This is like the first session with astronauts (running simulations).
- How is there no one waiting to start services? Does not match what we think we're doing in our team
- Can I click on more than one service at a time?
- Ability to switch between Service Proportions from Team Data or Appropriate Service Proportions from Supply is cool!
- Who defines what is appropriate service proportions?
- We need to get our patients back into PCMHI?
- What does the green mean?
- What is difference between red and green toggle sliders? They are the same items. Our hypothesis is if you want to make changes you toggle on the green.
- Talking about efficiencies we see some providers twiddling thumbs while others are on hamster wheel
- How do you run a basecase?
- I think our hypothesis is that we currently think our rates of referral don't match up with our appt supply. If we adjust our own referral rates, we'll achieve a new steady state with different proportions. 
- It changes because what we do as people is a workaround.  But that is suboptimal.  What we can do moving forward is find an optimal solution and apply that.
- What do we select on display patient services to run the experiment?
- How do we know if we ran it?
- What does number mean in the save tile? How do we save?
- What made the spikes in the basecase run?
- Would this be the same (the spike occuring) regardless of whether I ran this 3 months from now?
- If system will balance everything out anyway, why do I care?
- What do we think about changing? What are we able to change? How much are we changing?
- I can't change my grids. I can't change my tour. But I have to see 17 people with the time to see 5.
- When we make no new decisions with our current appt supply and patient demand for psy, access to psychotx worsens/wait times will double within 6 months from 2 to 4 weeks on our team. Didn't increase wait times for intake because 
- If we do nothing, it will get worse, but the system will conspire to get it at a level that is tolerable.
- Intake is the first things that happens when someone is new to MH. Intake doesn't happen again once on team. They may get cc, mm, psy, ebpsy, etc. or multiple things at once. Demands that are happening, happen amongst ourselves to meeting this patients' needs.
- Decisions: If we're doing this to ourselves, it means we could make different decisions within our team that would put supply and demand at a different level. I'd like to see what would happen if we start bringing psy patients back more frequently and  working to shorten time they're in care.
- Everyone is sharing patients. Everyone should be taking on the role of MHTC.
- Questions on difference between Service Proportions from Team Data vs. Appropriate Service Proportions from Supply
  - Current state vs. supply dicatated from current state
  - Where is green data coming from?
    - Coming from all of team data - appt supply, RVI, engagement duration, etc.
    - Data from team data table is being pulled in from data.
    - Individual proportions for green are calculated based on all the other data. Figure out for a team's situation how many patients the team can start. What percent of reviews/intakes can you send to the specific services based on supply, etc.
    - Green box is more realistic assessment of what you could be doing given all the interdependencies

## Session 8
Prep
- Review session guide as agenda
- Talk about last time
- Divide up Session 8 tasks
- Review Hypothesis and Decision
- Build new experiment on appointment supply and service proportions: shift psy appts to ebpsy

Session
- Agenda
- Today we're modeling to learn...
- Done/Do
- Review team questions/concerns from Session 7 and introduce what we will do this session
- Learning objectives
- Priorities last time were around access
- Everything we are doing will tie back to original question of how we increase access and how do we increase access to EBPsy
- Guide how to log in
- Review where we would see Q/H/F/D
- Review how to pull up previous experiment through Expanded Outputs tile and review ? symbol in the Alternatives section
- Review how to pull up previous experiment Q/H/F/D and values from the Experiments tile
- Review that we want to change psy and EBPsy
- Can change service proportions to idealized ratio from team data proportions
- How many slots do I need to increase to get to the ideal ratio?
- What does ideal ratio mean? I thought green isn't ideal, necessarily. It's optimized for what you have now.
- Can we swap CC and EBPsy?
- WHo can we afford to "bump out" more? Psy or CC?
- We don't really know what CC means
- Question: What happens if we icnrease appt supply for EBPsy and group, decrease the number of appointments for CC, and increase RVI for CC and PSY 
- Hypothesis: If we increase appointment supply for EBPsy to 8  and we decrease the number of appointments for CC to 2 and CC RVI out to 20 and decrease PSY to 5 appts/wk and change RVi to 1, increase group to 5 appts/week we expect to increase in wait times initially, increase appointments for EBPsy.
- Findings: We found that patients waiting for PSY increases temporarily but that improves over BC. Waiting for intake was "untouched" so it stayed the same. The patients ho are currently engaged went to 10. Work pressure - increases and then flattens out. Actual RVI - it increased for a couple of months, but then at about a year it decreaseds. If we do a better job of matching the service to the need, it gets worse in the short-term, but pays off in the long-run in the team. The chaos for EBPsy or Group is because we didn't refer more people in those groups.
- Decisions: EBPSy or Group have to change the service proportions for those
- Done/Do covered

## Facilitator Flip Chart Questions
1. MTL Language
- Tile is not intuitive and this language is distracting. Makes me think of bathroom or floor. Window or frame seems more intuitive. 
- I get that there won't be a "universal language" until we reinforce it. Story and system is non-intuitive. Trips me up a little each time.
- Explain "story" with beginning, middle, and end
- Would be helpful to have a place to click on where MTL language is explained
- Give team opportunity to read/digest theory articles (learner and facilitator)
2. Dynamics before Details
- I get it but will require practice and responsiveness to get the focus on bigger picture view. If there could be a mantra that could be developed for it.  
- Helpful to remind people that these are just experiments - no need to quibble over the numbers for too long.
- Helpful to tell people that we will come back to the details later. Acknowledging it is important but not priority right now.
- If people have ideas, they can always go into their individual worlds and run it.
- We do not want to reinforce by runinng useless experiments that this is one more tool that is not useful
- Committing to a hypothesis gives buy in to exploring the results

## Debrief
- Session 7 ran over time in part because of the model shift
- Tomorrow
  - Need to draft the evaluation form. Can be sourced from R21 pre/mid/post evaluation form.
  - Debbie will work on paired sequencing
  - Pull up Facilitator Dashboard tomorrow

## Tech Issues/Suggestions 
1. Notification in chat when someone sends a message
2. Why do green variables have BC in AGG? Why are the green BC values defined here and not in other places? Intake Evaluation Rate is also green with BC, but no way to find the value.
3. Agg Model Team Data Table - Appt Supply variables should have "75th percentile" label instead of "median"
4. Would be nice to have an "are you sure?" pop up for Run button
5. In MTL Facilitate Pilot Team Group in Worl 001 in Agg Model, there was a bug with the y axis scale for "Group - Actual Return Visit Interval"

