---
title: "Session 1 Script"
author: "Stacey Park"
date: "December 14, 2017"
output: 
  github_document: default
html_document: default
ioslides_presentation: default
slidy_presentation: default
pdf_document: default
---

# Modeling to Learn Session 1: Shared Interim Vision (TOTAL time 20 minutes)

We all learn best when we seek to accomplish things that matter to us. Today we want to clarify what we are trying to accomplish together with “Modeling to Learn.” We want this learning process to be something you can commit to because it reflects a key part your own vision for care in this team.  

Identifying a shared purpose can be deeply motivating, it requires mutual respect to find common ground and it is something to be created over time together, not just one time.  

That said, we want to take a few moments to begin to identify a shared purpose about what we are trying to achieve with this time. The team learning goal provides the focus and energy for committing to learning together over time. We have limited time, we want to identify what is most central to team learning goals and connect or to daily team care delivery.  

What is (retrospective data) versus what we would like it to be (future oriented). Team learning is all about ‘alignment’ and getting people working in synch with one another to meet the needs of our Veteran patients.  

Moving from “my vision” to “our vision” for continual team learning and improved care coordination, shift your paradigm towards how things could be done.  

With a shared vision everyone has a common destination and a common picture. They then work together as a team, supporting and encouraging each other. There is no competition between people, therefore there is no need to pass blame or hide your failures.  

Team lead and a facilitation team to figure our “What’s better?” in a way that reflects common team aspirations.  

## Prior Team Learning Prompt (5 minutes) - We want to set ground rules for our learning sessions too:  

Think of a good learning experience in your team. It can be in a meeting or an informal exchange with a colleague. It can be when your learned a clinic procedure, and idea for treatment with a difficult patient, or when a team member unlocked a mystery of CPRS for you. Try to think of a time when you had an ‘aha!’ or something finally made sense, or you could finally do something your couldn’t before.  

Jot down on scratch paper what it was that made it a good learning experience. What were the characteristics of the experience? Compile a team list:  

*Most likely the following is true:*   
* The learning was hands-on and experiential
* The learning connected to the real world
* The learning experience was personally relevant, interesting, useful, or meaningful to the learner
* The learner had choices, shared authority, control, and responsibility
* The learner learned from and taught others
* The learner had the support
* The learning was individualized. If there were standards for the work, the learner could meet them in his or her own way
* It was fun or left the learner feeling good
* The experience helped the learner understand him or herself
* The learner had success and accomplishment with challenging work

## Best Case Scenario - Create team language for learning, aligning team decisions when there are roadblocks to consensus:
Start by picturing Veteran mental health care in this team as you experience it now – the interactions/communications within the team in and out of team meetings, think about the key people you rely on outside the team, the information and data you use to coordinate care plans, and the feelings you associate with it.  

Now picture the team learning between now and March in a ‘best case’ scenario, where things are happening in the team the way that you would ideally like them to be. This is your “dream team” situation.  

## Personal Vision (5 minutes)  
* What is team communication like?
* How does the team relate to one another?
* How is VA data used?
* How are decisions, plans and changes made?

## Review in Team (5 minutes)  
* What stands out to you?
* Why did we choose these?
* What makes them so relevant or important to us?
* Can we address them all (bearing in mind our resources and time)?
* If not, which would we most like to address (align around), and why?

## Putting it Together - Overall “Modeling to Learn” Objectives (10 minutes)  
1.	Meaningful for you that aligns your learning goals with your team
2.	Systems thinking skills help to see how several things fit together, and understand causes hard to see without data and modeling resources.
3.	Transparent to you how this fits with VA data, initiatives and standards 
4.	Empowers you to realize ongoing improvements in team quality of care and team quality of work life

### Done   
* Team lead 
* Team folder 
* Team meeting - schedule, links, course outline

### Do  
* Team learning goal 
* Clinical case
* Data selected for simulation 


### Team Data Sharepoint
https://spsites.cdw.va.gov/sites/PTSD_OMHO/Pages/VISN21/640.aspx

### Adobe Connect
https://va-eerc-ees.adobeconnect.com/team_psd/
