## Introduction

    Providers, patients, policy makers and scientists each have a stake in ensuring all patients with opioid use disorder (OUD), alcohol use disorder (AUD), depression and posttraumatic stress disorder (PTSD), receive timely, evidence-based care. In the Veterans Health Administration (VA), these common, costly conditions comprise the majority of outpatient addiction/mental health needs (1–3). But highly effective treatments such as evidence-based psychotherapy (EBPsy) and evidence-based pharmacotherapy (EBPharm) reach only 3-28% of patients (4–6). National evidence-based practice (EBP) dissemination programs (7–11), policies (12–14), incentivized quality measures (15, 16), and EBP-focused electronic health records (17) have been insufficient to realize greater EBP reach (18–20), key to preventing chronic impairment, relapse, overdose, (21–23) and suicide (24–26) among Veterans.
    Like most health systems (27–29), VA uses team huddles and audit-and-feedback (AF) processes to coordinate and improve EBPsy/EBPharm care. But AF outcomes vary widely (30), with the least success for complex tasks like multidisciplinary EBP continuity and coordination (31). Research suggests that solving complex, multidisciplinary challenges such as team EBP delivery requires addressing system-level causes (35–40). Participatory System Dynamics (PSD) offers a method of active group learning, using system diagrams and simulation models (41, 42), that builds capacity for understanding and managing causal system dynamics (43, 44). Simulation modeling overcomes cognitive limitations (45, 46) to prospectively restructure delay and feedback dynamics that influence EBP reach over time (47). Using such models lets teams test their hypotheses and gain shared insights about how decisions within their control interact to affect outcomes they care about.

    The Modeling to Learn course leads front-line clinic staff, working together in their teams, through a progressive PSD process designed to:
    •	Enhance VA team members’ knowledge and skill in systems thinking; 
    •	Make VA data, initiatives and standards transparent to clinic staff;
    •	Help teams understand complex interactions among factors – including decisions within their control and resource limitations that constrain them – that are difficult, if not impossible, to see without data and models; and
    •	Empower teams to generate ongoing quality improvements in both patient care and work life.
    Four system dynamics models of limited EBP reach were developed by a team of stakeholders and other experts.
    •	Lindsey Zimmerman, PhD, Implementation Scientist, National Center for PTSD, Dissemination & Training Division (NCPTSD-DT) – Team PSD Project Lead and Principal Investigator
    •	Stacey Park, BA, Team PSD Project Administrator, NCPTSD-DT

    The models help explain “reach as a function of local front-line staff decisions and available resources (48, 49). Three focus on specific services: Care Coordination (CC), Medication Management (MM), and Psychotherapy (Psy). A fourth, Aggregate (Agg) model looks at combined services across a local VA mental/behavioral health clinic. 
    Existing VA health system data was extracted using standard definitions for diagnoses, appointments, visits and EBPs, and calculated model parameter values for local teams  (15, 50). Models define mechanisms identified by stakeholders using systems theory and calculus, which are validated against historical data (51). PSD learning is via real-time visual emergence of local causes of EBP reach in virtual experiments (52–54). Simulations are a safe way to build systems thinking into EBP decisions (44, 55, 56).

