---
title: "Modeling to Learn"
author: "Team Participatory System Dynamics"
date: "December 15, 2017"
output:  
beamer_presentation: default  
ioslides_presentation: default  
mode: self-contained  slidy_presentation: default

---
# "Modeling to Learn Facilitation Guide"

## "Table of Contents"

### Modeling to Learn Course Objectives

### Schedule Overview

#### Session 1 - Team Learning Goal

#### Session 2 - Introduction to Team Data

#### Session 3 - Review Team Data/Introducing Care Coordination Model

#### Session 4 - Care Coordination

#### Session 5 - Care Coordination

#### Session 6 - Medication Management

#### Session 7 - Medication Management

#### Session 8 - Psychotherapy

#### Session 9 - Psychotherapy

#### Session 10 - Aggregate

#### Session 11 - Aggregate

#### Session 12 - Wrap-up

### 508 Accessibility Standards

### Accredidation Requirements

### Vensim Model(s)

### Roles of Facilitator

#### Team Lead

#### Team Participation Requirements

### Modeling to Learn User-Interface Navigation

#### Page Groups & Flows

##### 2.02 Admin’s Dashboard / Administration Features / 5.2.1.
Basic Administrative Functionality for administration from the National Center
for PTSD

##### 2.02 Admin’s Dashboard / Administration Features / 5.6.2.
Overview page with list of users and their current progress

##### 2.03 Player’s Dashboard / 5.9.5 Timeline information,
tracking progress against schedule

##### 2.03 Player’s Dashboard / 5.9.10 Decisions Page

##### 2.03 Player’s Dashboard / 5.9.6 Dashboard with access to
key metrics

##### 2.03 Player’s Dashboard / 5.9.11 Copy data to clipboard

##### 2.03 Player’s Dashboard / 5.9.12 Ability to export data as
a Comma Separated Values (CSV) File

##### 2.03 Player’s Dashboard / 5.9.13 Players can create their
own scenarios for comparison in session

##### 2.04 Retune the Model for Different Locations  / 5.3.1 Framework for Multiple Cities,
States, other Locations AND 
##### 5.3.2 Ability to Upload Datasets by Location

##### 2.05 User Management 
/ 5.4.2 Upload List of Users from a Comma Separated Values (CSV) file

##### 2.05 User Management 
/ 5.9.4 Set team name

##### 2.06 Game Assignment / 5.4.1 Creating Classes &
Managing Different Classes (Provided by the Platform)

##### 2.09 Report / 5.9.7 In-game reports (assume 7 reports) AND

##### 2.07 Game Progress / 5.5.1 Compare scenario results AND
##### 2.07 Game Progress / 5.9.8 Scoring / Compare to Other Teams (Admin) AND
2.09 Report / 5.7.1 Decision Matrix by Team

##### 2.11 Chat Feature / 5.6.3 View/Send Messages to Teams or
Team Members AND 
##### 2.11 Chat Feature / 5.9.9 Chat Feature to Interact With Other Teams

