---
title: "Team Data Table"
author: "Savet Hong"
date: "March 22, 2018"
output: html_document
     
---

```{r setup, include=FALSE}

library(readxl)
library(dplyr)
library(tibble)
library(knitr)
library(kableExtra)

```

## Care Coordination Model


```{r cc_setup, include=FALSE}
ccpar <- read_excel("./original/modelparameters.xlsx", sheet = "CCParams", col_names = FALSE)
ccpar.table <- ccpar[c(12,10,5,3,1,7),] # Select row and order to match UI
ccpar.table$X__2 <- formatC(ccpar.table$X__2, digits = 2, format = "f")

```

#### CC Table without definition (similar to the UI)

```{r cc_table, echo=FALSE, include=FALSE}

kable(ccpar.table[,-3], col.names = c("",""), booktabs = TRUE, caption = "Team Data")  

```

```{r cc_table_NOdef, echo=FALSE}

htmlTable::htmlTable(ccpar.table[,-3], header = c("",""), rnames = FALSE, css.cell = "padding-left: 1em; padding-right: 1em;", caption ="Team Data", align = "lr")
```

#### CC Table with definition

```{r cc_table_def, echo=FALSE}
#kable(ccpar.table, col.names = c("","",""), caption = "Team Data")  

htmlTable::htmlTable(ccpar.table, header = c("","",""), rnames = FALSE, css.cell = "padding-left: 1em; padding-right: 1em;", caption ="Team Data", align = "lrl")
```

## Medication Management Model


```{r mm_setup, include=FALSE}
mmpar <- read_excel("./original/modelparameters.xlsx", sheet = "MMParams", col_names = FALSE, range = "A1:F16")

mmpar.table1 <- mmpar[c(10, 15, 12, 5, 3, 1, 13, 14), c(1,3,2,4:6)] 
              # Missing "Target Wait Time"


mmpar.table <- mmpar.table1 %>%
  mutate(X__5 = replace(X__5, X__1 == "Appointment Supply", 
                        X__2[which(X__1 == "Appointment Supply")]),
         X__2 = replace(X__2, X__1 == "Appointment Supply", NA),
         X__3 = replace(X__3, X__1 == "Appointment Supply", NA),
         X__4 = replace(X__4, X__1 == "Appointment Supply", NA),
         X__5 = replace(X__5, X__1 == "% Appointment Slots (has X-Waiver)",
                        X__2[which(X__1 == "% Appointment Slots (has X-Waiver)")]),
         X__2 = replace(X__2, X__1 == "% Appointment Slots (has X-Waiver)", NA)) %>%
  mutate_at(vars(2:5), funs(formatC(as.numeric(.),digits = 2, format = "f"))) %>%
  add_row(X__3 = "AUD", X__2 = "DEP", X__4 = "OUD", X__5 = "OTHER", .before = 3)

```

#### MM Table without definition (similar to the UI)

```{r mm_table, echo=FALSE, include= FALSE}
options(knitr.table.format = "html")
kable(mmpar.table[,-6], col.names = c(rep("",5)), caption = "Team Data" ) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```

```{r mm_table_NOdef, echo=FALSE}

htmlTable::htmlTable(mmpar.table[,-6], header = c(rep("",5)), rnames = FALSE, css.cell = "padding-left: 1em; padding-right: 1em;", caption ="Team Data", align = "lrrrr")

```

#### MM Table with definition

```{r mm_table_def, echo=FALSE}
#kable(mmpar.table, col.names = c(rep("",6)), caption = "Team Data" )

htmlTable::htmlTable(mmpar.table, header = c(rep("",6)), rnames = FALSE, css.cell = "padding-left: 1em; padding-right: 1em;", caption ="Team Data", align = "lrrrrl")

```


## Aggregate Model

```{r agg_setup, include=FALSE}
aggpar <- read_excel("./original/modelparameters.xlsx", sheet = "AggParams", col_names = FALSE, range = "A1:I12")

#Table data setup
aggpar.table.head <- aggpar[c(6,2),]
aggpar.table.body <- aggpar[c(2,1,5,3,4),] %>%
  mutate_at(vars(2:8), funs(formatC(as.numeric(.),digits = 2, format = "f"))) %>%
  rename(Intake = X__2, Psy = X__3, EBPsy = X__4, CC = X__5, MM = X__6, 
         Adjunctive = X__7, Group = X__8, Variable = X__1, Definition = X__9)

aggpar.table.body.shrt <- t(aggpar.table.body[,2:8]) 
colnames(aggpar.table.body.shrt) <- aggpar.table.body$Variable

aggpar.test <- as.data.frame(aggpar.table.body.shrt) %>%
  mutate(X__1 = row.names(.)) %>%
  select(X__1, everything()) %>%
  mutate_if(is.factor,funs(as.character)) %>%
  add_row(X__1 = as.character(aggpar[6,1]), `Appointment Supply` =
            as.character(aggpar[6,2]), 
          `True Missed Appointments %` = "Patients/Week",.before = 1) %>%
  add_row(`Appointment Supply` = "Appointment", `True Missed Appointments %` = 
           "True Missed",`Return Visit Interval` = "Return Visit", 
          `Median Engagement` = "Median", `Referral Percentage` = "Referral",
          .before = 2) %>%
  add_row(`Appointment Supply` = "Supply", `True Missed Appointments %` = 
           "Appointments %",`Return Visit Interval` = "Interval", 
          `Median Engagement` = "Engagement", `Referral Percentage` = "Percentage",
          .before = 3)

#Table definition
agg_def <- aggpar[c(6,2,1,5,3,4),c(1,9)]
```

#### Aggregate Table without definition (similar to the UI)

```{r agg_table, echo=FALSE}

#kable(aggpar.table.body.shrt, booktabs = TRUE, caption = "Team Data")  
#htmlTable::htmlTable(aggpar.table.body.shrt, css.cell = "padding-left: 1em; padding-right: 1em;", caption ="Team Data", align = "rrrrr")

htmlTable::htmlTable(aggpar.test, header = c(rep("",6)), rnames = FALSE, css.cell = "padding-left: 1em; padding-right: 1em;", caption ="Team Data", align = "lrrrr")


```
#### Aggregate Table Definition

```{r agg_table_def, echo=FALSE}
htmlTable::htmlTable(agg_def, header = c("Concept", "Definition"), rnames = FALSE, css.cell = "padding-left: 1em; padding-right: 1em;", caption ="Team Data: Aggregate Table Concept Definition", align = "ll")

```

## Psy Model

```{r psy_datafiles, include=FALSE}
psypar1a <- read_excel("./original/modelparameters.xlsx", sheet = "PSYParams", col_names = FALSE, range = "B35:D36")

psypar1b <- read_excel("./original/modelparameters.xlsx", sheet = "PSYParams", col_names = FALSE, range = "B40:D43")

flow <- read_excel("./original/modelparameters.xlsx", sheet = "PSYParams", col_names = FALSE, range = "B3:D7")

```

```{r psy_setup, include=FALSE}
ord1 <- c("Appt. Supply", "% AUD", "% DEP", "% OUD", "% PTSD")
psypar1 <- rbind.data.frame(psypar1a[1,], psypar1b) %>%
  mutate(X__1 = replace(X__1, X__1 == "PctPTSD", "% PTSD"),
         X__1 = replace(X__1, X__1 == "PctDep", "% DEP"),
         X__1 = replace(X__1, X__1 == "PctAUD", "% AUD"),
         X__1 = replace(X__1, X__1 == "PctOUD", "% OUD"),
         X__1 = replace(X__1, X__1 == "Baseline Appointment Supply", 
                        "Appt. Supply")) %>%
  mutate_if(is.numeric, funs(as.character)) %>%
  slice(match(ord1, X__1)) %>%
  mutate(X__2 == replace(X__2, X__1 == "Appt. Supply", 
                         paste0(X__2[which(X__1 == "Appt. Supply")], 
                                " Slots/Week")))
  
pflow <- flow

```

#### Psy Table without definition (similar to the UI)
```{r psy_table, echo=FALSE, include=FALSE}
# htmlTable::htmlTable(, header = c(rep("",6)), rnames = FALSE, css.cell = "padding-left: 1em; padding-right: 1em;", caption ="Team Data", align = "rrrrr")

```
