## What did you learn today?
1. How to access mtl.how/data
2. PSD = participatory system dynamics
3. Viz = visualization
4. How to filter data

## What do you want to learn more about?
1. Widening and narrowing aperture
2. Need concreteness - See data in action. Model how it would be done with a team. How team would use and apply data to answer question.
3. How to get buy in

## What else do we know to move forward tomorrow?
1. I want to be able to take a team's question or problem.  Walk us through the question/problem.
2. How to use tool to answer questions in the field.

## What are examples of questions you want answered?
1. How we increase access to EBP/all care in our BHIP team?
2. How do we get new patient wait times down?
3. How do I increase access to care when I'm required to increase open access?
4. When is a patient ready to step down to another service?
5. Want to drill down to..
- See patients
- Team/clinic from facility level
- See team trends
- See when we are serving our veterans
- Health Factors to see SAIL related data
- Clinicians ask how the denominator
6. What can I drill down to in the MTL Data UI that I can't already access from current platforms?

## Tech Issues/Suggestions
1. Trend charts not loading up and not changing
2. Gifs not moving on GitHub page
3. Addition of "clear all filters" button

## TeamPSD Debrief
- No one was able to fully pull up the Excel file for Session 2. As such, we did not get to any of the questions related to the Excel file.
- Many folks had concerns on seeing a question answered through the model.
- We need to talk more explicity about how the data UI and sim UI connect.
- Walk through SAIL question in team data table (on Psy, Suicide, --- framed as where would you look to find failing PSY 38?) in groups of 3 with one person "driving"
- Session 3 exercise - Turning data into estimates. Looking in Column C and D, and finding out how those estimates are made.
- TAS members could ask each other to look for items in the data UI




