## Sticky
1. PSD = Participatory System Dynamics
2. Web address
- mt.how/facilitate, data, sim
3. Data UI
- Drill down
- Filter
- Flags
- Health factors

## Questions & Notes
1. Hardcoding RVI as one for EBP, sends an unintended message that this is very important and that RVI for other types of encounters are not as critical (i.e. sends message that regular psychotx can happen whenever). But, in order to get the model to run, a value is necessary there since some places do EBP's so seldom that this may be 0.  Calli
2. Ask team to look through all the questions in mtl.how/menu before priortizing so they can think about it in comparison to each other  

**mtl.how/menu**  
- Clarifying frame of reference for answering questions, especially where there is a lot of variability
- Keeping in mind the specific mix of disciplinesi in the team and how needs vary per discipline

**mtl.how/sim**
- Individual world: For your own private play
- Team World: For facilitation, teaching, working as a team
- Chat function - First thing TAS team asked about, spent large portion of time clarifying team vs. facilitator chat
- Team chat: Between team lead and facilitator
  - Facilitator chat: Between facilitators
  - Change generic photo in mtl.how/sim to be genderless
- Team Data "i" = tells you where information came from for team data
- Experiment "i" = tells you what you're changing in the model when you adjust that variable in the experiment
- Default value for experiment values are..?
  - BC/basecase value if from team data (you can check the value in the team data table at the top)
    - Slider will not reflect the value of BC. It will be left most.
    - Red variables only
  - Default value if not from team data
    - Green and purple variables
- What are the colors?
  - Red = read in
  - Green = variable you can experiment with not pulled in from team data
  - Purple = always set as default at middle position (value = 1); dimesionless variable; allows you to experiment with the effects of one variable on another; effects that we know are important but don't have concrete data for
- What is team data for starting rate? Look at the "i" icon!
- Add to Facilitator script: Ability to select previous experiment runs to set values in Experiments tile to a previous run
- 3 Tiles in Play Screen: Main Tile, Outputs Tile, Experiments Tile
- Rates: Unit of time is in weeks (The time unit of week is best for mental visualization as each day varies a lot and too much has happened by end of a month)
- Complexity  vs. complicated
- Slider = something that can be experimented with in Experiments tile
- Care Coordination systems story: If I start overbooking, this increases appt supply, and decreases measured vs. actual time
- Signs on arrows: Causal effect, not just correlational; Direct vs. Inverse relationship; Same vs. Opposite relationship
- Dynamics before details: Looking at the larger cause/effect relationship before the detailed values
- Bathtub analogy for rates flowing in and out of stock: Rate of faucet filling tub vs. rate of drainage of tub
- We can say "impact" instead of "related to" since this is (multi)causality not correlational.
- Clinicians often feel disempowered by solutions/programs from leaderhips as they are presented to be "simple," but MTL addressed the complexity of the clinic

## Empty My Cup
- Time it takes for feedback to take effect
- What it means to increase target wait-time
- If it's an odd number of negatives than it's a balancing loop; even number of negatives is a reinforcing loop
- CC may be hard to explain given stop codes; SW/nursing work may be changing
- Need more examples
- Every system is perfectly designed to get outcome it gets
- How my team is put together
- Huge problem we see everywhere is that people don't get the flow component

## Debrief
- Telling the system story as a group (rather than in pairs) both helps TeamPSD members better understand the model and helps brings in the diverse expertise across the board in telling the story and answering questions
- We need to move on from CC to other models that are more relevant to the clinicans they work with/questions they get in the field. We will work on telling systems story for an Agg model.
- Session 7 tomorrow morning: Q and H for basecase. TeamPSD will facilitate the TAS team to understand that the Hypothesis for basecase will show a fluctuating and then stabilizing graph due to the balancing loops. Folks will run experiments on their own.
- Facilitate TAS team through Session 7-9 as a "learner" rather than "facilitator". To address time constraints, we can reduce the mutual learning.
- Goal for MTL Faciltate Pilot team by Friday: 
  - Describe MTL resources
  - Test team questions
  - Apply expertise as TAS on how the MTL rollout should look like
  - "Can I teach this with a MH SME?"
  - TAS being excited enough to keep going
- One person asked "are people really going to ask these questions? do they need to know this?"
  - Remind TAS that they will not be expected to be the systems SME
  - We need to try out the co-facilitation model (systems SME + MH SME) that we planned in this pilot
- Feedback that shifting from the "learner" role to the "facilitator" role is confusing
- TAS team has great facilitation skills already, but they need to learn what they need to facilitate. Focusing on that learning space is important in moving this forward. Orient them to space of "Questions you have today will be questions teams have in the future." They can write down questions they have as the "facilitator" role separately but encourage only asking "learner" questions and thinking in "learner" space.
- Basecase language - "no new decisions" instead of "no change"
- We want to give TAS team "as authentic learner experience as possible"
- Ask TAS teams to share their notes with us. Helps with both with tracking the week and what stood out to each person.
- Goal for end of Thursday: Are TAS folks able to pickup elements of systems thinking and levels of systems complexity by the end of the day? 
  
## Thursday Plan
- Have large sign at front to indicate to everyone whether they have "learner" or "facilitator" hat on
- folks who have not had chance to facilitate yet will co-facilitate Session 7 and 8 with a TeamPSD/systems SME.  We will model the co-facilitation plan.
  - Gives us pilot data on co-facilitation model
  - We model that folks who have missed part of the training can still do it
  - We model the co-facilitation model to folks in-person in front of everyone
  - Involves picking target hypothesis and findings to facilitate team through
  - Divvying up who will facilitate do/done, facilitate systems story, keep track of time, keep track of chat time
- Give team sticky notes they can write unanswered questions on and they will post them on respective flip charts during breaks - Flip chart 1)"learner" or 2)"facilitator" separated as 1)"prioritize now" or 2)"parking lot"
8:00-8:15a Sticky  
-- Session 7: David (Basecase co-facilitator) + MH SME --   
1. 8:15a-8:35a Pre-prep Session 7 - TAS watch 
2. 8:35-9:35a Session 7 - TAS wear learner hat
3. 9:35a-9:55a Debrief- TAS watch
4. 9:55a-10:10a Put up question stickies on flip chart
-- Session 8: Debbie (first experiment co-facilitator) + MH SME --  
5. 10:10a-10:30a Pre-prep Session 8 - TAS watch
6. 10:30a-11:30a Session 8 - TAS wear learner hat
7. 11:30a-11:50a Debrief Session 8 - TAS watch
8. 11:50a-12:50p Put up stickies and lunch
9. 12:00p-1:50p Session 9 (Compare alternatives)
10. 1:50p-2:50p Mutual Learning - Facilitating Experiments
11. 2:50p-3:05p Break
12. 3:05p-4:15p Mutual Learning - Systems thinking CFBT
13. 4:15p-4:30p Debrief/Empty your cup

**Session 7**
- Introduce Outputs tile
- Run basecase
- Enter Q/H/F/D for Base Case (bc) Run in Expanded Outputs Tile
  - Q: What does our basecase look like?
  - H: Our team's behavior will reach steady state.
  - F: Describe findings - oscillation and then steady state.
- "D" Decision on what to test in Experiment 1

**Session 8**
- Complete Exp 1
- Enter Q/H/F/D for Exp 1 in Expanded Outputs Tile
= View Exp 1 against BC in Results Dashboard
- Decide on Exp 2
- Look at Q/H/F/D for systems thinking levels

**Session 9**
- Run Exp 2
- Compare BC, Exp 1, and Exp 2

      - TAS post questions written down on stickies onto flip chart, sorting by 1) "learner" or "facilitator" and 2) "top priority" or "later/bike rack"

## Friday Plan
1. Order steps of MTL program (30 min)
2. PSY (1 hour)
3. Break (15 min)
4. MM (1 hour)
5. Empty my cup
6. Debrief & Next Steps (1 hour)
7. Certificate and Thank You (30 min)


## Tech Issues
1. Referral rate in Experiments Tile in CC model in team_mtl_facilitate_pilot_2018_09 world has "BC"
2. The "i" information for "Measured vs. Actual Time" in Care Coordination is incorret. The current definition is for wait time right.
3. "i" information in diagram is too complex - "Effect of Task Time on Missed Appointments"
4. "Appointments for existing patients" in MM model does not have "i" information
5. "Appointments used by existing patients" in PSY model does not have "i" information. 
6. PSY still says "Appointments used by existing patients" instead of "Appointments for existing patients" which we standardized to
7. Fix typos in mtl_fidelity.Rmd
8. Chat function: Team chat vs. facilitator chat
- WHy can team lead see/engage in both types of chats?
- Why can't facilitator see team chat?
- Dropdown in Facilitator view of chat shows all the team names for each person?
9. Results Dashboard Variable issue
- If in the aggregate model, someone cues up 6 variables they want to look at in the results dashboard and then they go back to the main tile to choose a different service, the results dashboard should have the same variables (should not default to any other list). The team shouldn't have to reset the variables everytime they switch services.
- There are default variables we want cued up. Currently these default variables show for Compare Services but not for Compare Experiments. A current "work around" is if you go to Compare Services first and then go back to Compare Experiments, it holds the default variables we want cued up.
- If I cue up results dashboard for Exp 1, will it pull up the 6 variables chosen for the Results Dashboard in the same way that the Q/H/F/D gets pulled up?
10. In MTL Facilitate Pilot Team group in Aggregate Model, the saved experiment (which show up in the Experiment Maintenance Tile) is not coming up in the Experiments Tile nor in the Expanded Outputs Tile alternatives section.


