---
title: 'TeamPSD: Five-year Plan/Timeline'
author: "TeamPSD"
date: "`r format(Sys.Date(), '%b %d, %Y')`"
output:
  html_document: default

---
  
```{r, include=FALSE}
library(tidyverse)
library(readxl)

#plan <- read_excel("U:\\mtl_5yrs_timeline.xlsx", sheet = "Sheet2", skip = 2)
#plan <- read_excel("U:\\mtl_5yrs_timeline.xlsx", sheet = "Sheet3", range = 'G1:K95' )
plan <- read_excel("mtl_5yrs_timeline.xlsx", sheet = "lag")

```
  
```{r, include=FALSE}
clev <- unique(plan$`Project Component`)
gplan <- plan %>%
  filter(!is.na(`Project Component`)) %>%
  mutate(Item = row_number(),
         Component = factor(`Project Component`, levels = clev)) %>%
  gather(state, date, "Start", "End")
```
  
```{r, echo=FALSE, warning=FALSE, message=FALSE}
vacol <- c("#003F72", "#0083BE", "#C4262E", "#772432", "#598527", "#f3cf45","#f7955b","#839097",
             "#dcddde", "#cccc99", "#bec292")
ggplot(gplan, aes(date, Activities, color = Component, group=Item)) +
  geom_line(size = 10) +
  labs(x="Project year", y=NULL, title="Project timeline") +
  scale_color_manual(values = vacol)

```


## Grant Update
```{r, echo=FALSE, warning=FALSE, message=FALSE}
grant <- gplan %>%
  filter(`Project Component` == "Grant Updates")

ggplot(grant, aes(date, Details, color = Activities, group=Item)) +
  geom_line(size = 10) +
  labs(x="Project year", y=NULL, title="Project timeline") +
  scale_color_manual(values = vacol)


```

## Study

```{r, echo=FALSE, warning=FALSE, message=FALSE}
study <- gplan %>%
  filter(`Project Component` == "Study")

ggplot(study, aes(date, Details, color = Activities, group=Item)) +
  geom_line(size = 10) +
  labs(x="Project year", y=NULL, title="Project timeline") +
  scale_color_manual(values = vacol)
```

  