# *Session 9 Mutual Learning Role Play – Interpreting Results AGG Model*

+ Laptop/Computer – with outputs screen showing base case and experiment 1

# Roles
+ F1 = Facilitator 1
+ F2 = Facilitator 2  
+ P = MTL Facilitate Workshop Participants  
+ MTL = MTL Team Members who serve as Workshop Participants

# Groups
* The large group is divided in to 3 smaller groups with one MTL and one workshop participant serving as facilitators. 
* The other participants and MTL facilitators are divided up as listed below. The MTL participants who are serving as part of the workshop participants will be called on by the F1 or F2 as needed to provide additional input, interpretation, guidance, etc. on the experiment results.
Group 1 | Group 2 | Group 3  
F1 = P | F1 = P | F1 = P  
F2 = P | F2 = P | F2 = P  
P = 3 P	| P = 3 P | P = 2 P  
MTL = LZ, DK | MTL = TR, SP | MTL = DL, JB  

# Activity – 3 Segments
* The purpose of this activity is to allow MTL Facilitate Workshop Participants to teach others how to interpret the information and results from MTL simulations.  
* The activity will be completed in 3 segments:  
1. base case review  
2. experiment 1 review  
3. experiment 2 – what variables to modify based on experiment 1 results review  
* After segment 1 is done, new Ps will fill the roles of F1 and F2 for segment 2.  
* After segment 2 is done, new Ps will fill the role of F1 and F2 for segment 3. In some cases, P will have to facilitate two times.  
* Each team will have a laptop on the expanded Outputs Tile or a screenshot of an expanded Outputs Tile with the base case and one experiment showing.  
+ Generate sample or trigger dialogue ½ page sheets from text below to give to participants to guide the activity.  

# *Segment 1 – Base Case Review*  
* F1 Sample Dialogue: Welcome. Today our goals for the team are to: 1) review our most recent BC run; 2) walk through the 1st experiment we ran last time; and 3) think about what our next experiment will be based on the results of the 1st experiment.  
* F2 Sample Dialogue: Let’s review the base case results from your team data. What do you see P NAME?  
* P:   Participant verbalizes what he/she sees in the base case…  
+ e.g., the appointment booking rate …  
+ e.g., it seems like there is a larger number of appointments in _______  
* F1:  What else do you see in the base case that strikes you?  
+ e.g., the return visit interval seems long, what can we do…  
+ e.g., can someone explain the sensitivities to me?  
F2: What do you see MTL?  
+ MTL representative may reflect. Could ask “I’d like to see the base case charts if you click on Services on the left side of the Output tile.” Discusses what they see and allows feedback from the other participants.  
+MTL take notes of questions asked.  

# *Segment 2 – Experiment #1 Review*  
+ **Note to MTL Team:** only give small hints to locate data or information; let the P’s talk through and explore together.  

* F1 Sample Dialogue:  Let’s go over experiment #1. Someone remind me where the starting numbers are for each experiment.  
+ P who volunteers walks the group through the base case numbers from team data.  
F1: Who wants to show me where we see what the variables that were changed to when we ran this experiment?  
+ P who volunteers points group to the tile on left side of output screen or to the dropdown box in the Experiment tile at the top to see what numbers were changed for the experiment.  
* F2: Let’s go back over to the charts on the Outputs screen and talk through the impact of the changes we made in Experiment #1.  
* F2: When you look at the results from Experiment #1 what patterns do you see in the results? What has changed or stayed the same? Why do you think __VARIABLE__ didn’t / did change?  
+ basic feedback example, P1:  I see that as the care coordination appt booking rate increases the appointments in in CC increases which makes perfect sense – the more you book, the more appointments you have to have.  
+ basic feedback example, P2: It looks like the down side of that is that even though the CC appt booking rate is increasing and appts in CC increase the appts that are available for new pts is decreasing and we don’t want that to happen do we?  
* F1: What do you see MTL?  
+ MTL representative reflects on differences between base case and Experiment #1 that may be important to the clinic team in the model.
F1: Let’s put some notes in the Our Findings and Our Decisions tiles on the Outputs tile.
+MTL take notes of questions asked.

# *Segment 3 – Setting Up Experiment #2*
* F1 Sample Intro Dialogue:  Now that we’ve reviewed experiment #1, it’s time to decide on the next experiment our team will run. Let’s look back at the team data in the main model tile. 
* F2 Sample Intro Dialogue:   What is everyone’s thoughts on what we should run next? **Call on Participants if necessary.**  
+ P volunteers talk through the next experiment.  
* F1 Sample Intro Dialogue: Are we agreed that our next experiment will be ___________?  

* F2 Sample Intro Dialogue: Let’s go back over to the Outputs screen and fill in the notes boxes. First, **Our Question** - what is the question we will explore?  
+ **A participant should type notes into the computer screen while the group drafts the question.**  

*F2: Next, let’s work on **Our Hypothesis** - what do we think will happen to the system story when we run this experiment?  
+ **Participants should talk through what they think will happen. Type notes into the computer screen when the group agrees on the hypothesis.**  

F1: Let’s try and save this information.  

+MTL take notes on the process for determining the question, the hypothesis, and of questions asked.  
