--- 
title: "Team PSD Manual"
author: "Team PSD"
date: "`r Sys.Date()`"
link-citations: yes
preview: yes
site: bookdown::bookdown_site
description: This is the Team PSD one stop shop.
---

# Preface

Welcome to your Bookdown

The **bookdown** package can be installed from CRAN or Github:

```{r eval=FALSE}
install.packages("bookdown", "HelpersMG", "readr")
# or the development version
# devtools::install_github("rstudio/bookdown")
```


```{r include=FALSE}
library(HelpersMG)
library(readr)
#Parse table of contents for documents to be downloaded
read_markdown <- function(file, trim_ws = TRUE, ...){
  if (length(file) > 1) {
    lines <- file
  } else {
    lines <- readr::read_lines(file)
  }
  lines <- lines[!grepl('^[[:blank:]+-=:_|]*$', lines)]
  lines <- gsub('(^\\s*?\\|)|(\\|\\s*?$)', '', lines)
  readr::read_delim(paste(lines, collapse = '\n'), delim = '|', 
                    trim_ws = trim_ws, ...)
}

# Parse URLs out of String and preserve order from table
parse_urls <- function(table){
  x <- vector()
  for(i in 1:ncol(table)){
    for(j in 1:nrow(table)){
      url = gsub("(?<=\\()[^()]*(?=\\))(*SKIP)(*F)|.", '', table[[j,i]], perl=T)
      if(grepl("\\.*md",url)){
        x <- c(x,url)
      }
    }
  }
  return(x)
}

#remove yaml from markdown
parse_yaml <- function(document){
  if(grepl("\\.*md", document) && !grepl("\\index\\.Rmd", document)){
    md <- read_file(document)
  #remove everything before the H1
    md_no_yaml <- sub(".*?#","#", x = md)
    writeLines(md_no_yaml, con=document, useBytes=T)
    print(md_no_yaml)
  }
}

# Point file name to the md file containing your table of contents.
table_of_contents = read_markdown("table_of_contents.rmd")

markdown_files = parse_urls(table_of_contents)
for(url in markdown_files){
    wget(url)
}

#remove yaml from files
for(file in list.files(getwd())){
  parse_yaml(file)
}

```