---
title: 'Cyberseminar: Participants'
author: "TeamPSD"
date: "May 11, 2019"
output: slidy_presentation
---

```{r lib, include=FALSE}
library(tidyverse)
library(readxl)
library(choroplethr)
library(choroplethrMaps)
library(wordcloud)


sem1 <- read_excel("Don't Guess_  - Registration Repo.xlsx", skip = 13)
sem2 <- read_excel("Introducing Measurement  - Registration Report.xlsx", skip = 13)
sem1_ad <- read_excel("Raw report data - session1.xlsx", sheet = "Attendees", skip = 7)


```

```{r setup, include=FALSE, echo=FALSE}
vacol <- c("#003F72", "#0083BE", "#C4262E", "#772432", "#598527", "#f3cf45",
           "#f7955b","#839097", "#dcddde", "#cccc99", "#bec292")

sem1 <- sem1 %>%
  mutate(seminar = "Test Dont Guess")
sem2 <- sem2 %>%
  mutate(seminar = "Introducing Measurement")

semall <- sem1 %>%
  bind_rows(sem2)

usem <- unique(semall$seminar) 

```

# Registered Attendee Information

## Job Title
```{r job, warning=FALSE, echo=FALSE}

jt <- semall %>%
  filter(!is.na(`Job Title`)) %>%
  mutate(`Job Title` = tolower(`Job Title`)) %>%
  group_by(seminar, `Job Title`) %>%
  summarise(freq = n())

jtc <- jt %>%
  group_by(`Job Title`) %>%
  summarise(n = sum(freq))


set.seed(1234)
for( i in 1:length(usem)){
  layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
  par(mar=rep(0, 4))
  plot.new()
  text(x=0.5, y=0.5, usem[i])
  wordcloud(words = jt[jt$seminar == usem[i],]$`Job Title`, 
            freq = jt[jt$seminar == usem[i],]$freq, 
            colors= vacol,
            main = usem[i])
}

{  layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
  par(mar=rep(0, 4))
  plot.new()
  text(x=0.5, y=0.5, "All Sessions")
  wordcloud(words = jtc$`Job Title`, freq = jtc$n, 
          colors= vacol)
  }

```


## Affiliated with VA 

```{r cars, echo=FALSE}
aff <- semall %>%
  group_by(seminar,`Are you affiliated with the VA?`) %>%
  summarise(freq = n()) %>%
  mutate(prop = round(100* (freq/sum(freq)),0))

ggplot(aff, aes(x = seminar, y = prop, fill = `Are you affiliated with the VA?`)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(y = "Proportion (%)") +
  scale_fill_manual( values = c("#003F72", "#0083BE"))
         
```

##	Organization

```{r org, echo=FALSE}
org <- semall %>%
  filter(!is.na(Organization)) %>%
  mutate(Organization = tolower(Organization)) %>%
  group_by(seminar, Organization) %>%
  summarise(freq = n())

orgc <- org %>%
  group_by(Organization) %>%
  summarise(n = sum(freq))


set.seed(1234)


for( i in 1:length(usem)){
  layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
  par(mar=rep(0, 4))
  plot.new()
  text(x=0.5, y=0.5, usem[i])
  wordcloud(words = org[org$seminar == usem[i],]$Organization, 
            freq = org[org$seminar == usem[i],]$freq, 
            colors= vacol,
            main = usem[i])
}

{  layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
  par(mar=rep(0, 4))
  plot.new()
  text(x=0.5, y=0.5, "All Sessions")
  wordcloud(words = orgc$Organization, freq = orgc$n, 
          colors= vacol)
  }



```

##	State
```{r state, warning=FALSE, echo=FALSE}
loc <- semall %>%
  filter(!is.na(`State/Province`)) %>%
  group_by(seminar,`State/Province`) %>%
  summarise(value = n()) %>%
  mutate(region = tolower(`State/Province`))

locc <- loc %>%
  group_by(region) %>%
  summarise(value = sum(value))


for( i in 1:length(usem)){
  #plot.new()
  smap <- state_choropleth(loc[loc$seminar == usem[1],],
                   title  = paste0("Location of Seminar Participants: ", usem[1]),
                   legend = "Participant")
  print(smap)

}


state_choropleth(locc, 
                 title  = "Location of Seminar Participants: All Sessions", 
                 legend = "Participant") 

```

# Attendee Information

```{r att_setup, include=FALSE}
sem_sess <- paste0("session",1:4)
files <- list.files()
files <- files[sapply(sem_sess, function(y) grep(y,files)[1])] 
files <- files[!is.na(files)]

att_read <- function(x){
  dt <- read_excel(files[x], sheet = "Attendees", skip =  7)
  dt <- dt %>%
    mutate(seminar = sem_sess[x])
  return(dt)
}

poll_read <- function(x){
  dt <- read_excel(files[x], sheet = "Poll replies")
  dt <- dt %>%
    gather(question, response) %>%
    group_by(question, response) %>%
    tally() %>%
    mutate(seminar = sem_sess[x]) %>%
    filter(!is.na(response))
  return(dt)  
}

feed_read <- function(x){
  dt <- read_excel(files[x], sheet = "Feedback", skip = 1)
  dt <- dt %>%
    gather(question, response) %>%
    group_by(question, response) %>%
    tally() %>%
    mutate(seminar = sem_sess[x]) %>%
    filter(!is.na(response))
  return(dt)  
}

sem_ad <- do.call("rbind", lapply(1:length(files), att_read))
sem_poll <- do.call("rbind", lapply(1:length(files), poll_read))
sem_feed <- do.call("rbind", lapply(1:length(files), feed_read))


```


## Title
```{r job_att, echo=FALSE}
jt <- sem_ad %>%
  filter(!is.na(`Job Title`)) %>%
  mutate(`Job Title` = tolower(`Job Title`)) %>%
  group_by(seminar, `Job Title`) %>%
  summarise(freq = n())

jtc <- jt %>%
  group_by(`Job Title`) %>%
  summarise(n = sum(freq))


set.seed(1234)
for( i in 1:length(files)){
  layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
  par(mar=rep(0, 4))
  plot.new()
  text(x=0.5, y=0.5, sem_sess[i])
  wordcloud(words = jt[jt$seminar == sem_sess[i],]$`Job Title`, 
            freq = jt[jt$seminar == sem_sess[i],]$freq, 
            colors= vacol,
            main = sem_sess[i])
}

{  layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
  par(mar=rep(0, 4))
  plot.new()
  text(x=0.5, y=0.5, "All Sessions")
  wordcloud(words = jtc$`Job Title`, freq = jtc$n, 
          colors= vacol)
  }
```


## Poll Responses

Number of Responses to the Poll

```{r poll_n, echo=FALSE}
tb_poll <- sem_poll %>%
  group_by(seminar, question) %>%
  summarise(`Number of response` = n())
  

knitr::kable(tb_poll)
```


```{r poll, echo=FALSE}
pq <- unique(sem_poll$question) 

for( i in 1:length(pq)){
  poll <- ggplot(sem_poll[sem_poll$question==pq[i],], aes(response, n, 
                                                          fill = response)) +
    geom_bar(stat = "identity") +
    #scale_fill_manual(vacol) +  
    coord_flip() +  
    theme(legend.position = "none") +
    labs(x = "", y ="Number of Responses", title = pq[i])
  
  print(poll)

}

```



## Feedback Responses

Number of Responses to the Poll

```{r feed_n, echo=FALSE}
tb_feed <- sem_feed %>%
  group_by(seminar, question) %>%
  summarise(`Number of response` = n())
  

knitr::kable(tb_feed)
```


```{r feedback, echo=FALSE}
fq <- unique(sem_feed$question) 

for( i in 1:length(fq)){
  feed <- ggplot(sem_feed[sem_feed$question==fq[i],], aes(response, n,
                                                          fill = response)) +
    geom_bar(stat = "identity") +
    #scale_fill_manual(vacol) +
    coord_flip() +
    theme(legend.position = "none") +
    labs(x = "", y ="Number of Responses", title = fq[i])

  print(feed)
  
  # tb_feed <- sem_feed
  # 
  # knitr::kable(tb_feed)
}

```

